### ISSUE TITLE
Some language labels are not translated into German

### ISSUE THREAD

**Issue by medarob** [TYPO3GmbH/blog#1]
Hi,

I'm not sure if that is a bug but some language labels for the German language are not translated, for example:
![grafik](https://user-images.githubusercontent.com/33951787/52348504-c7283100-2a24-11e9-85e8-d5f88f5d8b11.png)

The discussion on slack: https://typo3.slack.com/conversation/C1XLMLRM1/p1549458020157500

TYPO3 Version: 8.7.24
Blog: 8.7.3

Best regards :)

**Comment by benjaminkott** [comment]
@medarob thx for the report, we checked and completed the German translation on https://translation.typo3.org/de/TYPO3.ext.blog/

Feel free to make suggestions if you think we translated something wrong.
