### ISSUE TITLE
Plugin ListPostsByAuthor

### ISSUE THREAD

**Issue by hweckhardt** [TYPO3GmbH/blog#104]
# Bug Report
I am not sure whether this is a bug or some settings are missing or wrong.
## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

Link from the Blog Post - Author Plugin - calls the right authors details page. The author details page contains the plugin List by Author. I expected the display of some authors details and the list of the posts related to this author. However, only a list of all authors is displayed. It seems, that condition="author" in Template ListPostByAuthors.html is missed.

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

List of the posts related to the linked author is shown.

**Actual behavior:** [What actually happened]

Only list of the names of all authors is shown.

## Versions
10.0.0.dev

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by hweckhardt** [comment]
I have found out, that the effect described before occurs, when the "Author Detail Page" is set in the "Authors Page", tab "Blog Data".

**Comment by benjaminkott** [comment]
There is currently no support to have a list of posts by an author. The detail page is to be filled with custom elements, if you do not need this you can simply reply on the default detail page that is generated. This contains basic information and a list of the posts.
