### ISSUE TITLE
Translatable Comment Form Error Messages

### ISSUE THREAD

**Issue by danielDigitalArt** [TYPO3GmbH/blog#105]
# Feature Request

I found that the Error Messages of the Comment form are not translatable, the Errors are defined in the templatefile: typo3conf/ext/blog/Resources/Private/Partials/General/FormErrors.html
These Messages are not included by "f:translate" but by a simple "`<li><span>{error}</span></li>`" thus these can not be translated.

Version: 
blog: 9.1.2
Typo3: 9.5.2

**Comment by benjaminkott** [comment]
@danielDigitalArt thx for reporting we rebuild the complete comment form rendering in master already to use the form famework, also be also translatable that way. This should solve your issue, check it out and let us know what you think. We are not planning to provide backports for this for blog versions below v10.

😊💖
