### ISSUE TITLE
FLUIDTEMPLATE is not in use

### ISSUE THREAD

**Issue by greiling** [TYPO3GmbH/blog#110]
# Bug Report

## Prerequisites
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

Trying to deactivate comments - or the meta-part "comment" I was faced to not to change behaviour via FLUIDTEMPLATE - even the extension "blog_template" use 

<f:cObject typoscriptObjectPath="tt_content.list.20.blog_meta" />
which is a USER-func and not strict FLUID.

I could not find any documentation to get the "blog"-extension alive without blog_template. "Customizable Templates" - no!

## Steps to Reproduce

1. install blog
2. setup a blog
3. try to figger out, if you can remove "0 comments" without touching extensions PHP code.

**Expected behavior:** [What you expected to happen]
  <f:render partial="Post/Meta" arguments="{_all}" />

**Actual behavior:** [What actually happened]
  <f:cObject typoscriptObjectPath="tt_content.list.20.blog_meta" />

TS_setup_config - trying to substitute blog_template:

 copy of public/typo3conf/ext/blog/Resources in fileadmin/ext/blog_ohne_kommentare/Resources/ a

> plugin.tx_blog {
>     persistence {
>         storagePid = {$plugin.tx_blog.settings.storagePid}
>     }
> }
> 
> 
> lib.pageid = TEXT
> lib.pageid.data = page:uid
> 
> lib.blogid = TEXT
> lib.blogid.value < plugin.tx_blog.settings.blogUid
> 
> plugin.tx_blog {
>   _LOCAL_LANG.de {
>     headline.sidebar = BIB-Blog
>   }
> }
> plugin.tx_blog {
>   _LOCAL_LANG.default {
>     headline.sidebar = BIB blog
>   }
> }
> 
> 
> 
> 
> tt_content.list.20.blog_links = HMENU
> tt_content.list.20.blog_links {
>   1 = TMENU
>   
>   1.wrap = <aside class="tx-blog-widget"><h3 class="widget-title">Pflichtangaben des Betreibers</h3><ul>|</ul></aside>
>   1.expAll = 1
>   1.NO.allWrap = <li>|</li>
> }
> 
> plugin.tx_blog.settings.sidebarWidgets.70 = tt_content.list.20.blog_links
> plugin.tx_blog.settings.sidebarWidgets.40 >
> 
> 
> blog = PAGE
> blog {
>     config.noPageTitle = 2
>     headerData {
>         # title tag
>         10 = TEXT
>         10.data = page:title // page:navtitle
>         10.stdWrap.override.cObject < lib.metaData
>         10.stdWrap.override.cObject {
>             key = title
>         }
>         10.wrap = <title>|</title>
>         # meta description
>         20 = TEXT
>         20.data = page:description
>         20.stdWrap.override.cObject < lib.metaData
>         20.stdWrap.override.cObject {
>             key = description
>         }
>         20.wrap = <meta name="description" content="|" />
>         30 = TEXT
>         30.value < lib.canoncicalUrl
>         30.wrap = <link rel="canonical" href="|" />
>         # OG-Tags
>         110 = TEXT
>         110.value = de_DE
>         110.wrap = <meta property="og:locale" content="|" />
>         120 = TEXT
>         120.value = article
>         120.wrap = <meta property="og:type" content="|" />
> 
>         150 = TEXT
>         150.value < lib.canoncicalUrl
>         150.wrap = <meta property="og:url" content="|" />
>         160 = TEXT
>         160.value < sitetitle
>         160.wrap = <meta property="og:site_name" content="|" />
>         170 = TEXT
>         170.data = page:tstamp
>         170.date = c
>         170.stdWrap.override.cObject < lib.metaData
>         170.stdWrap.override.cObject {
>             key = modified_date
>         }
>         170.wrap = <meta property="og:updated_time" content="|" />
> 
>         240 = TEXT
>         240.data = page:crdate
>         240.date = c
>         240.stdWrap.override.cObject < lib.metaData
>         240.stdWrap.override.cObject {
>             key = published_date
>         }
>         240.wrap = <meta property="article:published" content="|" />
>         250 = TEXT
>         250.data = page:tstamp
>         250.date = c
>         250.stdWrap.override.cObject < lib.metaData
>         250.stdWrap.override.cObject {
>             key = modified_date
>         }
>         250.wrap = <meta property="article:modified" content="|" />
> 
>     }
>     10 = FLUIDTEMPLATE
>     10 {
>       
>        settings {
>          	link4home = {$plugin.tx_blog.settings.link4home}
> 			text4home = {$plugin.tx_blog.settings.text4home}
>  			home = {$plugin.tx_blog.settings.home}
>        }
> #      file = EXT:blog_template/Resources/Private/Template.html
>         templateName = Default
>       	templateRootPaths.10 = fileadmin/ext/blog_ohne_kommentare/Resources/Private/Templates/
>         partialRootPaths.10 =  fileadmin/ext/blog_ohne_kommentare/Resources/Private/Partials/
>         layoutRootPaths.10 = fileadmin/ext/blog_ohne_kommentare/Resources/Private/Layouts/
>     }
> }

## Versions
algo26-matthias/idna-convert   v1.1.0  A library for encoding and decoding internationalized domain names
cogpowered/finediff            0.3.1   PHP implementation of a Fine granularity Diff engine
doctrine/annotations           v1.7.0  Docblock Annotations Parser
doctrine/cache                 v1.8.0  Caching library offering an object-oriented API for many cache backends
doctrine/dbal                  v2.9.2  Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/event-manager         v1.0.0  Doctrine Event Manager component
doctrine/instantiator          1.2.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                 1.1.0   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
guzzlehttp/guzzle              6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises            v1.3.1  Guzzle promises library
guzzlehttp/psr7                1.6.1   PSR-7 message implementation that also provides common utility methods
helhum/config-loader           v0.12.2 Generic config loader with context and environment support.
helhum/typo3-console           v5.7.2  A reliable and powerful command line interface for TYPO3 CMS
helhum/typo3-console-plugin    v2.0.5  Installer plugin for helhum/typo3-console, to ease usage without the need to specify scripts in your root composer.json
nikic/php-parser               v4.2.3  A PHP parser written in PHP
nseibert/ldap                  v3.3.6  TYPO3 LDAP extension
psr/cache                      1.0.1   Common interface for caching libraries
psr/container                  1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/http-message               1.0.1   Common interface for HTTP messages
psr/http-server-handler        1.0.1   Common interface for HTTP server-side request handler
psr/http-server-middleware     1.0.1   Common interface for HTTP server-side middleware
psr/log                        1.0.2   Common interface for logging libraries
ralouphie/getallheaders        3.0.3   A polyfill for getallheaders.
reelworx/rx-shariff            v12.1.0 Shariff implementation for TYPO3 CMS including the backend module, a viewhelper and a plugin.
swiftmailer/swiftmailer        v5.4.12 Swiftmailer, free feature-rich PHP mailer
symfony/cache                  v4.3.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts        v1.1.5  Generic abstractions related to caching
symfony/console                v4.3.4  Symfony Console Component
symfony/expression-language    v4.3.4  Symfony ExpressionLanguage Component
symfony/finder                 v4.3.4  Symfony Finder Component
symfony/intl                   v4.3.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/polyfill-ctype         v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu      v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn      v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring      v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72         v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73         v1.12.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                v4.3.4  Symfony Process Component
symfony/routing                v4.3.4  Symfony Routing Component
symfony/service-contracts      v1.1.6  Generic abstractions related to writing services
symfony/var-exporter           v4.3.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/yaml                   v4.3.4  Symfony Yaml Component
t3g/blog                       9.1.2   This blog extension uses TYPO3s core concepts and elements to provide a full-blown blog that users of TYPO3 can instantly understand and use.
t3g/blog-template              1.2.3   blog template extension
typo3/class-alias-loader       1.0.1   Amends the composer class loader to support class aliases to provide backwards compatibility for packages
typo3/cms-about                v9.5.9  Shows info about TYPO3, installed extensions and a separate module for available modules.
typo3/cms-adminpanel           v9.5.9  The TYPO3 admin panel provides a panel with additional functionality in the frontend (Debugging, Caching, Preview...)
typo3/cms-backend              v9.5.9  Classes for the TYPO3 backend.
typo3/cms-belog                v9.5.9  Displays backend log, both per page and system wide. Available as the module Tools>Log (system wide overview) and Web>Info/Log (page relative overview).
typo3/cms-beuser               v9.5.9  Backend user administration and overview. Allows you to compare the settings of users and verify their permissions and see who is online.
typo3/cms-cli                  2.0.0   TYPO3 command line binary
typo3/cms-composer-installers  v2.2.2  TYPO3 CMS Installers
typo3/cms-core                 v9.5.9  The core library of TYPO3.
typo3/cms-extbase              v9.5.9  A framework to build extensions for TYPO3 CMS.
typo3/cms-extensionmanager     v9.5.9  TYPO3 Extension Manager
typo3/cms-felogin              v9.5.9  A template-based plugin to log in Website Users in the Frontend
typo3/cms-filelist             v9.5.9  Listing of files in the directory
typo3/cms-fluid                v9.5.9  Fluid is a next-generation templating engine which makes the life of extension authors a lot easier!
typo3/cms-fluid-styled-content v9.5.9  A set of common content elements based on Fluid for Frontend output.
typo3/cms-form                 v9.5.9  Form Library, Plugin and Editor
typo3/cms-frontend             v9.5.9  Classes for the frontend of TYPO3.
typo3/cms-impexp               v9.5.9  Import and Export of records from TYPO3 in a custom serialized format (.T3D) for data exchange with other TYPO3 systems.
typo3/cms-info                 v9.5.9  Shows various infos
typo3/cms-install              v9.5.9  The Install Tool mounted as the module Tools>Install in TYPO3.
typo3/cms-lowlevel             v9.5.9  Enables the 'Config' and 'DB Check' modules for technical analysis of the system. This includes raw database search, checking relations, counting pages and ...
typo3/cms-recordlist           v9.5.9  List of database-records
typo3/cms-redirects            v9.5.9  Custom redirects in TYPO3.
typo3/cms-reports              v9.5.9  The reports module groups several system reports.
typo3/cms-rte-ckeditor         v9.5.9  Integration of CKEditor as Rich Text Editor.
typo3/cms-scheduler            v9.5.9  The TYPO3 Scheduler let's you register tasks to happen at a specific time
typo3/cms-seo                  v9.5.9  SEO features for TYPO3.
typo3/cms-setup                v9.5.9  Allows users to edit a limited set of options for their user profile, eg. preferred language and their name and email address.
typo3/cms-sys-note             v9.5.9  Records with messages which can be placed on any page and contain instructions or other information related to a page or section.
typo3/cms-t3editor             v9.5.9  JavaScript-driven editor with syntax highlighting and codecompletion. Based on CodeMirror.
typo3/cms-tstemplate           v9.5.9  Framework for management of TypoScript template records for the CMS frontend.
typo3/cms-viewpage             v9.5.9  Shows the frontend webpage inside the backend frameset.
typo3/minimal                  v9.5.0  Minimal required set of TYPO3 extensions
typo3/phar-stream-wrapper      v3.1.2  Interceptors for PHP's native phar:// stream handling
typo3fluid/fluid               2.6.1   The TYPO3 Fluid template rendering engine

**Comment by benjaminkott** [comment]
@greiling thx for reporting this should be fixed in master, we got brand new templates and options to customize the style of displaying meta data within the post header and footer. I am closing this issue for now, please let me know what you think about the enhancements 👍.
