### ISSUE TITLE
Add a search plugin

### ISSUE THREAD

**Issue by maechler** [TYPO3GmbH/blog#114]
It would be nice if there was a frontend plugin `Blog: Search` with the following features:

- Full text search for posts (optionally including authors, tags and categories)
- Filter for categories, tags and authors
- TypoScript settings to toggle which filters are shown and whether to show full text search or not

**Comment by cogtail** [comment]
Perhaps ke_search could offer corresponding possibilities. What do you think?

**Comment by maechler** [comment]
I do not know `ke_search`, but I will have a look at it, thanks! Nevertheless I think the blog extension should already include such a feature without relying on a third party extension.

**Comment by thdieden** [comment]
I think the opposite is true. Search algorithms require a lot of performance, and it's good to encapsulate them in a plugin of your own that is dedicated exclusively to this task. It would be a nightmare if each plugin implemented its own search.

**Comment by benjaminkott** [comment]
We are not planing to build a search solution, please use indexed_search, ke_search or other search implementation.
