### ISSUE TITLE
Comments Active Default Value

### ISSUE THREAD

**Issue by chriskrj** [TYPO3GmbH/blog#116]
Hey, i tried to override the default Value of the comment Active field in Table pages.

i tried to use TCADefaults or the option in tsconfig file. Both does not have any effect.  Blog Pages still are created with comments_active = 1 

Is there a different way to override this Value? 
For other TYPO3 Fields this Methode works fine.

BR
Chris

Environment: 
TYPO3 9.5.10
Php 7.2
tx_blog: 9.1.2

**Comment by benjaminkott** [comment]
Seems to be related to a core issue that TCADefaults is not working:
https://forge.typo3.org/issues/89211

Will provide a workaround to configure this for the instance.

**Comment by prathers** [comment]
I'm facing problems with the 
`plugin.tx_blog.settings.comments.active = 0`
It still shows a "0 comments" in frontend, regardless the settings

Environment:
TYPO3 8.7.31
Php 7.2.21
tx_blog: 8.7.6

**Comment by benjaminkott** [comment]
@chriskrj TCADefaults issue seems to be resolved with:
https://github.com/TYPO3/TYPO3.CMS/commit/bbc6800b382ef90cbe2a02ec039be23529de468c

@prathers it´s best working in master branch for blog, we needed to do a lot of adjustments that are breaking in terms of templates behave. Please adjust your templates manually if you need this change.
