### ISSUE TITLE
Tags are not limited by storage pid

### ISSUE THREAD

**Issue by Andreas-Sommer** [TYPO3GmbH/blog#122]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

Tags are not limited by storage pid wich is odd in multip domain purpose

## Fix
https://github.com/belsignum/blog/commit/6f799fad9e6b64571a1ebefda0a46ca5423637fc

**Comment by Isaegenuet** [comment]
I would be grateful if the bugfix would be implemented.
Thank you in advance

René
