### ISSUE TITLE
TCA limitation of authors to PAGE_TSCONFIG_ID

### ISSUE THREAD

**Issue by Andreas-Sommer** [TYPO3GmbH/blog#123]
Should be as all other relations limited to PAGE_TSCONFIG_ID
https://github.com/belsignum/blog/commit/07cae89ebb4202537952c10fbd34e80a2577258e

**Comment by benjaminkott** [comment]
@Andreas-Sommer thanks for reporting this issue! Should now be fixed 😀💖.
