### ISSUE TITLE
Archive: The search result for displaying posts by year is incorrect

### ISSUE THREAD

**Issue by thdieden** [TYPO3GmbH/blog#126]
# Bug Report
Bug in function PostRepository::findByMonthAndYear(). If month is null, $year has to be set as value to calculate the variable $startDate.

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

**Expected behavior:** For a selected year, the archive should contain all the posts of that year.

**Actual behavior:** The archive shows for a selected year all posts older than the selected year.

## Versions

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by benjaminkott** [comment]
This issue should already be resolved with #127 
Thx a lot for reporting 😊💖.
