### ISSUE TITLE
Page properties: "Author" field should be filtered by language.

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3GmbH/blog#138]
# Bug Report

* TYPO3 10.3
* t3g/blog dev-master 4a40a31 (Current commit as of today, 2020-03-18.)

## Description

When editing a blog page, in the blog tab there is a `selectMultipleSideBySide` field `authors`.
The available items are not filtered by language.

Author translations were requested at https://github.com/TYPO3GmbH/blog/issues/91 and merged at https://github.com/TYPO3GmbH/blog/pull/118 .

## Steps to Reproduce

1. Set up a TYPO3 10.3 site with multi-language support.
2. Install and configure the blog extension (`t3g/blog dev-master 4a40a31`).
3. Make an author in the blog storage folder.
4. Translate them to a secondary site language.
5. Make a new blog page.
6. Switch to the "Blog" tab in the page properties.
7. Find that the "Author" select field shows authors in duplicates: Both the original and the translated version are selectable.

**Expected behavior:**

Only the authors of the current language are shown.

**Actual behavior:**

Authors of all languages are shown.

A `foreign_table_where` is missing in `Configuration/TCA/Overrides/pages.php`:
```
        'authors' => [
            'exclude' => 1,
            'label' => $ll . 'pages.authors',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'multiple' => 0,
                'foreign_table' => 'tx_blog_domain_model_author',
                'MM' => 'tx_blog_post_author_mm',
                'minitems' => 0,
                'maxitems' => 99999,
                'behaviour' => [
                    'allowLanguageSynchronization' => true
                ]
            ],
        ],
```

The `tags` column is configured with a language filter:
```
'foreign_table_where' => 'AND tx_blog_domain_model_tag.sys_language_uid IN (0,-1) AND tx_blog_domain_model_tag.pid = ###PAGE_TSCONFIG_ID### ORDER BY tx_blog_domain_model_tag.title ASC',
```

**Comment by benjaminkott** [comment]
@LeoniePhiline thx a lot for this wonderful bug report, issue is fixed in upstream 😊💖.
