### ISSUE TITLE
problem with resolving current post with multilanguage setups

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3GmbH/blog#14]
A user reported an issue in slack:

> Raphael Weber [01:33 Uhr]
> Lately I have a bug (I guess?) with TYPO3 9.5.4 and blog 9.1.0 (same with T3 9.5.3 and blog 9.0.1 too):
> On the detail page of a blog I used to place the “authors” frontend plugin which does show the author as it should in the main language. Unfortunately it does not show the author in the translated language anymore. It worked fine in TYPO3 7.x. But now there is a `<div>` tag with the corresponding id and a child element `<a>`-tag with the origin language content uid but it is empty. I am guessing it has something to do with the authors not being translateabel objects? Did anyone experience this behaviour before? Anything I could to to narrow it down further?
> (done all upgrade-wizzard-thingies, cleared all caches, deactivated custom templating overrides, deleted and recreated the plugin-content-object on the detail pages) 

I can reproduce the problem and debugged the SQL query.

The findCurrentPost method in the PostRepository return null in case of a translated page / post. Further investigations are required.

----

blocked by TGT-1505 we decided to wait until this issue is solved, before we try to find and fix the issue in extbase.

----

Reporter: Frank Nägler

Created:	5 days ago
Updated:	Yesterday

Development: EXTBLOG-153

**Comment by raphaelweber** [comment]
duplicate: https://github.com/TYPO3GmbH/blog/issues/3
