### ISSUE TITLE
SetupWizard puts Example "First blog post" in wrong directory (version 8.7.6)

### ISSUE THREAD

**Issue by AlexanderKoe** [TYPO3GmbH/blog#140]
a simple issue: using the SetupWizard and creating a blog, the example page "First blog post" is stored outside the data directory. So the frontend result is "This list contains no blog posts."

a easy fix, but confuses me on my first steps :)
maybe already fixed in 9.x versions which I cannot test without a TYPO3 9
thanks for your work

--
TYPO3 v8.7.30 LTS wiht blog 8.7.6
Newer Versions on TYPO3 9 not tested because I did't have one

**Comment by LeoniePhiline** [comment]
@AlexanderKoe Better update asap. TYPO3 8 LTS does not even receive security fixes any longer.

**Comment by Lefaux** [comment]
This information is not entirely correct. TYPO3 8 is now in its ELTS stage, so there is still the option to access security fixes via a subscription

**Comment by benjaminkott** [comment]
We are sorry for the inconvenience, setup was reworked for the next release. Unfortunately we will not adjust this for older versions. If you like to patch it yourself, we will have a look and consider a new release for this.
