### ISSUE TITLE
author was added automatically and shown in author list in BE

### ISSUE THREAD

**Issue by medarob** [TYPO3GmbH/blog#145]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

We recently noticed that authors were added automatically to blog post in the backend.

## Steps to Reproduce

I opened the site properties of the blogpost: -> tab "blog" and wanted to add an author to the blogpost.

I select an author on the right side and this author was added to the left side.
![grafik](https://user-images.githubusercontent.com/33951787/80006645-7683e300-84c5-11ea-8324-af2cfc88df7c.png)

I press the [save] Button and now another author is shown at the left side.

![grafik](https://user-images.githubusercontent.com/33951787/80006980-ebefb380-84c5-11ea-9df8-8acb2a8f4a59.png)

**Expected behavior:**

Only the selected authors are shown on the left side.

**Actual behavior:**

Now two authors are shown in the Backend.

Luckily only the author which I have selected is shown in the frontend and not both authors.
But I think this is still a bug in the backend.

The author which was added additionally was logged in as admin and tried what I described here.

## Versions
blog 9.1.2
TYPO3 9.5.15

I'm not sure if this behaviour existed already in an earlier version.

**Comment by ajikmi** [comment]
i have the same Problem. Tags doing same issue.

**Comment by medarob** [comment]
Despite my initial finding, it seems like that both authors are shown in the frontend:
![grafik](https://user-images.githubusercontent.com/33951787/81432263-ea2f1c80-9162-11ea-91fc-238a7b0be759.png)

The second author is the original author and the first author was added automatically.
The blog posts seems random.

I can also click on the author to see a list of post the author has never written.

**Comment by benjaminkott** [comment]
should be resolved with https://github.com/TYPO3/TYPO3.CMS/commit/ce50ca1259
