### ISSUE TITLE
Change slug evaluation from uniqueInSite to unique

### ISSUE THREAD

**Issue by georgringer** [TYPO3GmbH/blog#149]
Please checkout https://github.com/georgringer/news/blob/master/Documentation/Misc/Changelog/8-2-0.rst and change the evaluation accordingly from uniqueInSite to unique!

**Comment by benjaminkott** [comment]
We do not plan to support categories or other slugs across multiple sites out of the box. If this behavior is necessary, the user needs to take care of this. 

a. Change slug configuration to unique
b. Provide advanced route configuration to include the uid´s of the category so it can be resolved
