### ISSUE TITLE
Problem with routing of archive

### ISSUE THREAD

**Issue by criwe** [TYPO3GmbH/blog#153]
# Bug Report

## Prerequisites

* [x ] Can you reproduce the problem on **TYPO3 v10.4.4 LTS**
* [ x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

I used the master to update the blog extension for TYPO3 10.4.4. 
Everything works great exept the routing of the archive URLs (2020, 2019...) doesn´t work. I used the content of the BlogArchive.yaml in my siteconfig. When calling a page with the sidebar the following error ocurs:

![Zwischenablage01](https://user-images.githubusercontent.com/7531138/84935868-a8867f80-b0d9-11ea-8941-33384a12f0be.png)

(or from the errorlog:

 {"exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException: Parameter \"tx_blog_archive__year\" for route \"tx_blog_archive_0\" must match \"[0-9]{1..4}\" (\"2020\" given) to generate a corresponding URL. in /vendor/symfony/routing/Generator/UrlGenerator.php:193\nStack trace:\n#0 /typo3/sysext/core/Classes/Routing/UrlGenerator.php(55): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'tx_blog_archive...', 1, Array, Array)\n#1 /vendor/symfony/routing/Generator/UrlGenerator.php(160): TYPO3\\CMS\\Core\\Routing\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'tx_blog_archive...', 1, Array, Array)\n#2 /typo3/sysext/core/Classes/Routing/PageRouter.php(329): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('tx_blog_archive...', Array, 1)\n#3 
}

A link without the routing looks like https://domain.tld/blog/archiv/?tx_blog_archive%5Baction%5D=listPostsByDate&tx_blog_archive%5Bcontroller%5D=Post&tx_blog_archive%5Byear%5D=2020&cHash=48898321bef04c6bbb2e17750c3bcac7 and works fine.

## Steps to Reproduce

1. Integrate content of BlogArchive.yaml in siteconfig
2. call a site where archive Links (the years) are shown

**Expected behavior:** [What you expected to happen]

should generate speaking urls

**Actual behavior:** [What actually happened]

throws an error

Best,
Christoph

**Comment by medarob** [comment]
please check if this fix helps: https://github.com/TYPO3GmbH/blog/pull/151

**Comment by criwe** [comment]
Hi @medarob 
yes, that fixed my problem.
Thanks a lot!
Best,
Christoph
