### ISSUE TITLE
Update Download link in extension manual

### ISSUE THREAD

**Issue by linawolf** [TYPO3GmbH/blog#174]
# Bug Report
On the docu page https://docs.typo3.org/p/t3g/blog/master/en-us/Administrators/Index.html# 
the extension download is linked to the old outdated link:

https://typo3.org/extensions/repository/view/blog/current/

Please update it to 

https://extensions.typo3.org/extension/blog/

the old link doesn't work anymore.

**Comment by gilbertsoft** [comment]
![grafik](https://user-images.githubusercontent.com/25326036/101346994-ae3f6f80-3889-11eb-9d17-e8e8ca06ebfb.png)

**Comment by andreasfernandez** [comment]
The documentation has been rewritten and the mentioned link does not occur anymore, thus I'll close this ticket.
Please see the chapter "Installation" at https://docs.typo3.org/p/t3g/blog/master/en-us/Installation/Index.html.

Kind regards
Andreas
