### ISSUE TITLE
TypeError in PostRepository::findRelatedPosts() due to strings passed by PostController::relatedPostsAction()

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3GmbH/blog#18]
In `\T3G\AgencyPack\Blog\Controller\PostController::relatedPostsAction()`, `\T3G\AgencyPack\Blog\Domain\Repository\PostRepository::findRelatedPosts()` hits me up with a `TypeError`, because its (actually `int`) arguments are passed as strings from typoscript ( `$this->settings['relatedPosts']['categoryMultiplier']`).

----

Frank Nägler added a comment - 28.01.19 08:39

As already mentioned in slack, I would prefer a (int) cast in front of each argument instead of the solution in your branch (https://bitbucket.org/awooooo/blog/commits/b57bc095ee0e11d98ddb8e5754b2f0f8179fc36f?at=bugfix/TE-111). Anyway many thanks for your contribution.

----

Cookie added a comment - 29.01.19 19:38

Copied from Slack, just for completeness:

Maybe you missed that on a quick glance, but there is indeed an (int) cast before the settings access. However, if the value happened to not be set, then "" would be cast to 0, which is a bad default. Therefore, I looked up and applied the defaults from the TS constants.

This all is not because of my personal preference, but to fit in with the code style of the project - access to $this->settings is rare in this project, but it is solved exactly as I re-created in my branch in the pre-existing https://bitbucket.typo3.com/projects/EXT/repos/blog/browse/Classes/Controller/WidgetController.php#121-123,159,177-178 .

If the (int)$this->settings['relatedPosts']['limit'] ?: 5 bothers your, then it might make sense to change it in WidgetController as well, in order to keep a consistent code style.

----

Reporter: Cookie

Created:	27.01.19 16:40
Updated:	29.01.19 19:38

Service-Desk: TE-111

**Comment by LeoniePhiline** [comment]
After moving to gihub, the former bitbucket.typo3.com link is: https://github.com/TYPO3GmbH/blog/blob/50e0f1584fb17aef666436552a111c8067f8d548/Classes/Controller/WidgetController.php#L105-L107

**Comment by benjaminkott** [comment]
@LeoniePhilineI guess you are the original author? Can you send a pr for this one?

**Comment by LeoniePhiline** [comment]
Yep - I'll need to first move that over to github as well. I can PR tomorrow.

**Comment by LeoniePhiline** [comment]
There's a partial approach merged:
https://github.com/TYPO3GmbH/blog/commit/09b617f00acc72a614263dc13c833ef62add9f34

Would you want the defaults, like in WidgetController? (see https://github.com/TYPO3GmbH/blog/issues/18#issuecomment-461109350)

**Comment by LeoniePhiline** [comment]
This seems fixed.

**Comment by benjaminkott** [comment]
thx @LeoniePhiline was fixed in https://github.com/TYPO3GmbH/blog/commit/09b617f00acc72a614263dc13c833ef62add9f34
