### ISSUE TITLE
"Add Image" button not visible after deleting author image

### ISSUE THREAD

**Issue by luis-pato** [TYPO3GmbH/blog#183]
# Bug Report
Once we delete an author image the "Add Image" and "Select & Upload Files" buttons are missing. (Please see Screenshot)

![image](https://user-images.githubusercontent.com/42058106/105360092-7fdae100-5bf8-11eb-9e48-9d57ac3825f0.png)

## Description

After deleting a blog author image we can't see the "add image" or "select & upload files" buttons. To see the buttons we first need to save and reload the frame. Then the buttons are visible and we can add a new image.

## Steps to Reproduce

1. Add an image to a blog author and save
2. Delete author image (buttons missing)
3. save and reload frame (buttons again visible)

**Expected behavior:**
I would expect the buttons to be immediately available after we delete the image.

**Actual behavior:**
After deleting the image we first need to save and reload the frame to see the buttons again

## Versions
**t3g/blog**: version: v10.0.x-dev
**TYPO3:** version: 10.4.12

**Comment by KaffDaddy** [comment]
It`s an TYPO3 bug: https://forge.typo3.org/issues/93293
Because of the maxitems parameter in the TCA for the image field of tx_blog_domain_model_author.

**Comment by Lefaux** [comment]
Thanks @KaffDaddy for double-checking and linking the issue here.
