### ISSUE TITLE
Archive Blogwidgetlist__itemtitle First Entry or March/März is empty

### ISSUE THREAD

**Issue by roemer-ag** [TYPO3GmbH/blog#191]
Good Morning and thank you for your great Extension!
In the Sidebar > Archive the first Month-Entry (for March) is empty. The following Month are shown correctly. 
So you have any Idea?
Thank you very much.
<img width="1023" alt="Bildschirmfoto 2021-03-31 um 09 02 22" src="https://user-images.githubusercontent.com/58509756/113104993-6a3df500-9201-11eb-9400-89a130db4b6e.png">

**Comment by helsner** [comment]
can confirm, had the same issue, but didn't solve it and now i cannot find it again..
Could this be a PHP / locale issue or something non related to blog?

**Comment by roemer-ag** [comment]
It appears on a live-Website/Mittwald-Server. I am curious to see what happens tomorrow (next Month) = only first entry of the List or especially the Month March....?

**Comment by roemer-ag** [comment]
Exactly what I was thinking... but could not solve it by my self (me = integrator). Do you have any Hints/Tips for me?

**Comment by helsner** [comment]
Sadly i also don't quite know how the issue occurs.
My best guess would be the locales setting in your site configuration which might be off.
so i check with "locale -a" on the server which locale is the right one and place it into the site config setting for that
But that's just some "ok thats the only thing i know that could help and if not then i dont know" 😅

**Comment by roemer-ag** [comment]
:) oke Thank you a lot - I will give it a try (next week).

**Comment by roemer-ag** [comment]
Tatatatataaaaataaaaa!
Exactly what you suggested: **locale** => **de_DE.utf8** gets the Job done. 
So it was my Misconfiguration not the Extension... but probably usefull for someone else.
Once again = THANK YOU
<img width="268" alt="Bildschirmfoto 2021-04-01 um 08 29 36" src="https://user-images.githubusercontent.com/58509756/113253029-f533f380-92c4-11eb-9a4e-b001388eb897.png">
<img width="559" alt="Bildschirmfoto 2021-04-01 um 08 30 15" src="https://user-images.githubusercontent.com/58509756/113253031-f5cc8a00-92c4-11eb-9f28-2aba1b4d4f05.png">
