### ISSUE TITLE
Speaking URL path segment for categories, tags and authors

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3GmbH/blog#21]
With the current configuration it is not possible to create a URL like https://www.example.de/blog/category/typo3-ist-toll from a title like "TYPO3 ist toll", but only https://www.example.de/blog/category/TYPO3 ist toll. This is because there is no speaking url path segment for categories, tags and authors.

Enclosed is already a working example of categories.

----

René Gast added a comment - 19.11.18 14:54

[blog.zip](https://github.com/TYPO3GmbH/blog/files/2837531/blog.zip)

----

Frank Nägler added a comment - 20.11.18 08:51

Hi Rene,
Thank you for the patch, can you provide a pull request with this changes?
It would also be nice to have this not only for categories, but also for tags and authors.
I checked the ZIP file, this contains only the changes for the categories, right?

----

René Gast added a comment - 20.11.18 10:38

Hi Frank,

you're right!

And I would like to do that, but it does not quite work. Currently I can use the path segment for the tags, but not the path generation with the type "slug" (here I get the error "Language -1 does not exist on site website.").

----

René Gast added a comment - 20.11.18 18:24

Hi Frank,

I've also created path segments for the tags and authors. The commented out details (languageField, transOrigPointerField, transOrigDiffSourceField as well as eval) caused me problems. The path generation for the authors is not working properly, at least the automatically generated path is strange (default-c6935384e0). In the appendix I attached the current changes, at the same time created a pull request.

[blog_2.zip](https://github.com/TYPO3GmbH/blog/files/2837540/blog_2.zip)

----

Hi Frank,

I've also created path segments for the tags and authors. The commented out details (languageField, transOrigPointerField, transOrigDiffSourceField as well as eval) caused me problems. The path generation for the authors is not working properly, at least the automatically generated path is strange (default-c6935384e0). In the appendix I attached the current changes, at the same time created a pull request.

----

Frank Nägler added a comment - 22.11.18 11:52

Hi Rene,
thanks, but I can't see any pull request, where do you created the pull request?

----

René Gast added a comment - 22.11.18 18:36

Hi Frank, maybe I can't create a pull request, because I can't fork the repository. I gave the patch anyway to my developer, because there are still some bugs. Alternatively, he can do the pull request.

----

René Gast added a comment - 26.11.18 17:38

My developer also worried about where the fork can be created. Therefore, I hereby send the new version. Please push it into the git by yourself. The path segments work for tags, categories and authors.

[blog_final.zip](https://github.com/TYPO3GmbH/blog/files/2837547/blog_final.zip)

----

Reporter: René Gast

Created:	19.11.18 14:54
Updated:	26.11.18 17:38

Service-Desk: TE-102

**Comment by dmitryd** [comment]
Probably it is better to call the field `slug`, same like in TYPO3.

**Comment by benjaminkott** [comment]
resolved with : https://github.com/TYPO3GmbH/blog/commit/ec79f882a5db4ba040f4293869207d5c89148d04
