### ISSUE TITLE
`Private/PHP/vendor/autoload.php` gets loaded in composer mode

### ISSUE THREAD

**Issue by twojtylak** [TYPO3GmbH/blog#212]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 v11.x
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

`Private/PHP/vendor/autoload.php` gets loaded in composer mode

## Steps to Reproduce

1. Install & activate extension 
2. Set breakpoint in `ext_localconf.php`

**Expected behavior:** [What you expected to happen]

`Private/PHP/vendor/autoload.php` should not be required if PSR- interfaces are available

**Actual behavior:** [What actually happened]

`Private/PHP/vendor/autoload.php` is required even if 

## Versions

10.0

**Comment by mbrodala** [comment]
I noticed the same issue when setting up Sentry. Since both the blog package and my actual root package provide a `InstalledVersions` class, somehow the one from the blog package was used. This lead to errors since basically no package was installed from the `InstalledVersions` POV.

That's why we are using the following workaround patch ATM:

```diff
diff --git ext_localconf.php ext_localconf.php
index bd09126..6599f1d 100644
--- a/ext_localconf.php
+++ ext_localconf.php
@@ -11,16 +11,6 @@ if (!defined('TYPO3_MODE')) {
     die('Access denied.');
 }
 
-/***************
- * Load Dependencies
- */
-if (!class_exists('Psr\Http\Client\ClientInterface') ||
-    !class_exists('Psr\Http\Message\RequestInterface') ||
-    !class_exists('Psr\Http\Message\RequestFactoryInterface')
-) {
-    require_once \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('blog') . '/Resources/Private/PHP/vendor/autoload.php';
-}
-
 /***************
  * Make the extension configuration accessible
  */
```

**Comment by mbrodala** [comment]
And the reason is the use of `class_exists()` instead of `interface_exists()` as mentioned in #213 :facepalm:

**Comment by mbrodala** [comment]
@andreasfernandez You can close this one now I'd say.
