### ISSUE TITLE
How to modify 

### ISSUE THREAD

**Issue by derBoogie** [TYPO3GmbH/blog#214]
# Support
Hi,
I need to modify the post meta data of blog pages in backend, but can't find the right fluid template.
![grafik](https://user-images.githubusercontent.com/1611217/126466230-fe09d3dd-d083-4821-8206-067c1d6cc0ef.png)
Can someone give me a hint in which backend template this output is generated?
Thanks!

**Comment by helsner** [comment]
PHP: \T3G\AgencyPack\Blog\Hooks\PageLayoutHeaderHook
HTML: blog/Resources/Private/Templates/PageLayout/Header.html

At least thats what i would guess

**Comment by derBoogie** [comment]
Thanks @helsner, that's the right place =)
