### ISSUE TITLE
Extend TCA

### ISSUE THREAD

**Issue by derBoogie** [TYPO3GmbH/blog#215]
# Support
Hi,
I implemented an own authors section with DCE.
This works fine but I'm not able to extend the blog tab in page properties with TCA.
If I use DOKTYPE_BLOG_POST in addToAllTCAtypes, then my custom field tx_sitepackage_authors is not shown at all.
Without the specific doktype my custom field is shown in the "Extended" tab.
Here is my TCA configuration:
```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('pages', [
  'tx_sitepackage_authors' => [
    'exclude' => true,
    'label' => 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_db.xlf:pages.authors',
    'config' => [
      'type' => 'select',
      'renderType' => 'selectSingleBox',
      'foreign_table' => 'tt_content',
      'foreign_table_where' => "AND CType = 'dce_contact' AND tt_content.pid = ###PAGE_TSCONFIG_ID### AND tt_content.sys_language_uid IN (-1,###REC_FIELD_sys_language_uid###)",
      'itemsProcFunc' => Vendor\Sitepackage\Filter\DceFilter::class . '->itemsProcFunc',
      'size' => 5
    ]
  ]
]);

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
  'pages',
  'tx_sitepackage_authors',
  (string) \T3G\AgencyPack\Blog\Constants::DOKTYPE_BLOG_POST,
  'replace:authors'
);
```

Is there anything missing?

**Comment by helsner** [comment]
be aware of the different page types blog_post  and blog_page IIRC
maybe you got the wrong one?

**Comment by derBoogie** [comment]
Hi @helsner,
thanks for your fast reply.

The page type of blog posts (doktype) is 137 or DOKTYPE_BLOG_POST, so this should fit.

I thought about whether the order of embedding static templates might be wrong, but my "sitepackage" extension comes at the very end, see screenshot:
![grafik](https://user-images.githubusercontent.com/1611217/126536453-b598d564-836b-43c4-8ad1-d158ad8aeb6a.png)

Could it be that the doktype does not know the new field tx_sitepackage_authors. Does this have to be registered first?
And If so, how?

**Comment by helsner** [comment]
the order should be displayed via PackageStates.php - but you can ensure your package is loaded after the blog one when you add the blog package as a dependency to your ext_emconf.php

**Comment by derBoogie** [comment]
@helsner you saved my day!
According to PackageStates.php, my sitepackage ext was loaded after the blog ext. I have now entered the dependecy of blog-ext into my ext_emconf.php, and now it works.
Thank you very much for the quick and competent help!
