### ISSUE TITLE
How to Config limit of Blogpost in a Plugin (Latest, Author,..)

### ISSUE THREAD

**Issue by ohm-meter** [TYPO3GmbH/blog#220]
# Support

How can i set a Limit of Post in a Plugin ? Or is this only possible via Config ?

Thanks...

**Comment by helsner** [comment]
`$this->settings['lists']['posts']['maximumDisplayedItems']`

https://docs.typo3.org/p/t3g/blog/master/en-us/Configuration/Index.html?highlight=maximumdisplayeditems#plugin-tx-blog-settings-lists-posts-maximumdisplayeditems

**Comment by helsner** [comment]
also see two lines below in the docs, there ist latestPosts.limit mentioned as well

**Comment by ohm-meter** [comment]
Thanks,

So it is only possible via TS Config.

Can i add some Flexform for that ?
