### ISSUE TITLE
How do i create an Author?

### ISSUE THREAD

**Issue by harp71** [TYPO3GmbH/blog#222]
# Support

Hi, how do i create an author-record? List-Module, New Record? I can´t find any blog-related records to create:

![grafik](https://user-images.githubusercontent.com/11310456/131884120-a754e668-d3ff-4a95-b046-c13312549fea.png)

Is it my typo3 or how is it done!?

HarP

**Comment by helsner** [comment]
Are you admin? because in case not you're might missing the rights for that

**Comment by harp71** [comment]
I´m admin! So how can it be? The templating is done via extension, not by me. I never experienced that an admin can´t see certain records. Where do i look?

**Comment by helsner** [comment]
Dont know either
on what page are you trying to create the record?
i can only create authors on folders, so maybe thats the issue

**Comment by harp71** [comment]
Yes, i tried everything, first on folders. Maybe someone knows why they aren´t showing up ...

**Comment by helsner** [comment]
I guess you added the typoscript etc. as template include? maybe that helps or just disabling & enabling the extension to make sure there were no loading issues that are still active

**Comment by harp71** [comment]
that´s the problem: i inherited that webiste from another developer. i don´t know where to look. i have no idea how you would even disable that for admins.

**Comment by helsner** [comment]
ah.. thats valuable information as the situation is not "i installed it" but "i overtook it with whatever config"
It could be a pagetsconfig setting? not sure about that, but that you can check for via info module.
Pagets config is either done in your code or even in the BE - there it might be within usergroups or per page properties definition.
As mentioned the info module could help you there, other than that you might want to write a query to check your BE usergroups or pages (or simply click through them)
Not sure about the whole pagets config thing though! i don't want to mislead you there, so you might check if it is possible

**Comment by harp71** [comment]
LOL ... thats what i call steering someone in the right direction. i added one # in a tsconfig-file to disable that line:

mod.web_list.allowedNewTables = pages,tt_content,sys_note

thank you so much for the support.
