### ISSUE TITLE
Error after install Version 11.0.0 on TYPO3 10 Last Version

### ISSUE THREAD

**Issue by edekowalski** [TYPO3GmbH/blog#230]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ X ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 v11.x
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description
![bugreport](https://user-images.githubusercontent.com/2975173/142203461-cc230f69-19e0-4775-812b-8503426ec5dc.JPG)

Error see screenshot attached

## Steps to Reproduce

1. After installation on my VM if got this error Messag
## Versions
11.0.0

**Comment by benjaminkott** [comment]
Can verify the issue, will investigate, and provide a fix. Thx for the report. 👍
