### ISSUE TITLE
Pagination not respected

### ISSUE THREAD

**Issue by mbrodala** [TYPO3GmbH/blog#234]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 v11.x
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

The integrated pagination is not applied when navigating between pages. The blog always lists the same most recent entries on all pages.

## Steps to Reproduce

1. Create at least 11 blog posts
2. Open the FE with a "recent posts" plugin
2. Click on page **2** within the pagination
3. See the URL change to include the pagination parameters (or route when using a route enhancer)

**Expected behavior:** Entry 11 and older should be shown.

**Actual behavior:** Entry 1-10 are always shown, no matter the page

## Versions

t3g/blog: 11.0.2
typo3/cms-core: v10.4.21

**Comment by mbrodala** [comment]
Small investigation so far: `$currentPage` arrives in the controller action and is also applied to the pagination object. I didn't have time to dig further than that yet.

**Comment by benjaminkott** [comment]
Had a quick test trying to evaluate the issue.

![image](https://user-images.githubusercontent.com/3243119/144564995-d3e1d4a6-73fc-4d69-b0bb-64443e72dbdf.png)

```
https://blog-10.ddev.site/autogenerated-1/?tx_blog_posts%5Bcontroller%5D=Post&tx_blog_posts%5BcurrentPage%5D=1&cHash=ff0731309a3b3085def84fcbdcea1ab8
```
![image](https://user-images.githubusercontent.com/3243119/144565154-ae37b550-7b0f-4ca5-a1c7-6b3566e30cb4.png)

```
https://blog-10.ddev.site/autogenerated-1/?tx_blog_posts%5Bcontroller%5D=Post&tx_blog_posts%5BcurrentPage%5D=2&cHash=c0c5559f78a31a1c88f7f348068bbde8
```
![image](https://user-images.githubusercontent.com/3243119/144565188-7651e970-2387-4aff-bca9-095c441fb313.png)

**Comment by mbrodala** [comment]
OK, let me retry on a barebone TYPO3v10 instance.

**Comment by mbrodala** [comment]
Works fine here, let me dig a little further what happens in our instance. If it is a local issue, I'll close this one.

**Comment by mbrodala** [comment]
Looks like the issue are quite a few template/partial overrides here which need to be updated for version 11 of the blog.

So very likely not an issue in the blog itself, thanks for checking!
