### ISSUE TITLE
PHP warnings about undefined array keys (PHP 8.0)

### ISSUE THREAD

**Issue by DavidVoi** [TYPO3GmbH/blog#245]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Can you reproduce the problem on TYPO3 v11.x
* [X] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

I'm seeing multiple PHP warnings about an array supposedly not being defined:
```
Undefined array key "doktype" in /{...}/typo3conf/ext/blog/Classes/ExpressionLanguage/BlogVariableProvider.php line 26
Undefined array key "doktype" in /{...}/typo3conf/ext/blog/Classes/ExpressionLanguage/BlogVariableProvider.php line 35
```

Additionally, these warnings , also about undefined arrays:
```
Core: Error handler (FE): PHP Warning: Undefined array key "T3G\AgencyPack\Blog\Notification\CommentAddedNotification" in (...)/typo3conf/ext/blog/Classes/Notification/NotificationManager.php line 27 	
Core: Error handler (FE): PHP Warning: Undefined array key "storagePid" in (...)/typo3conf/ext/blog/Classes/Domain/Repository/CategoryRepository.php line 35 	
Core: Error handler (FE): PHP Warning: Undefined array key "cssSourceMapping" in (...)/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 59 	
Core: Error handler (FE): PHP Warning: Undefined array key "overrideParserVariables" in (...)/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 58 	
Core: Error handler (FE): PHP Warning: Undefined array key "cssSourceMapping" in (...)/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 59 	
Core: Error handler (FE): PHP Warning: Undefined array key "overrideParserVariables" in (...)/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 58 
```
No warnings after downgrading PHP to 7.4

## Steps to Reproduce

1. Install extension in a minimal system (only one page, one folder)
2. Perform manual setup

**Expected behavior:** Extension should work fine and log a warning once in a while

**Actual behavior:** Extension seems to works fine, but logs multiple warnings.

## Versions

11.0.2

## Possible relations

**Fix PHP8 undefined array key warning in various places**
https://forge.typo3.org/issues/94542

**Comment by LeoniePhiline** [comment]
Note: To trigger this bug, a condition `[blog.isPage()]` (or `[blog.isPost()]`) must be used in TypoScript.

The warning is triggered when this expression language condition is evaluated while `$GLOBALS['TSFE']` is `null`, e.g. in backend context:

```php
    /**
     * @return bool
     */
    public function isPost(): bool
    {
        $page = $GLOBALS['TSFE']->page ?? [];
        return $page['doktype'] == Constants::DOKTYPE_BLOG_POST;
    }

    /**
     * @return bool
     */
    public function isPage(): bool
    {
        $page = $GLOBALS['TSFE']->page ?? [];
        return $page['doktype'] == Constants::DOKTYPE_BLOG_PAGE;
    }
```

![image](https://user-images.githubusercontent.com/22329650/195429986-e3068c87-c9d6-47a8-88c3-00c5ba01d139.png)

**Comment by LeoniePhiline** [comment]
Use of `$GLOBALS['TSFE']` should be expanded for backend contexts, e.g. like here: https://github.com/TYPO3GmbH/blog/pull/238/files#diff-3d23fcd0d1b8c49226b2c2237167a4526dc72a664fef65d40cd4eab10118c2a7R31

**Comment by SchoolGuy** [comment]
This hit me today too and we have a duplicate for this issue: #260

**Comment by SchoolGuy** [comment]
@LeoniePhiline Any idea how we can pour your information into a PR that then makes it into a bugfix release? This is still very annoying for me...

**Comment by LeoniePhiline** [comment]
The maintainers seem to have no interest in this issue, so I must assume preparing a PR might be useless. I'd say maintain a fork.

**Comment by SchoolGuy** [comment]
@LeoniePhiline A fork is not really in question for me. It is a private blog and I have a lot of other projects to maintain as well... :/
