### ISSUE TITLE
No valid wizard identifier given

### ISSUE THREAD

**Issue by Andreas-Sommer** [TYPO3GmbH/blog#256]
# Bug Report

## Prerequisites

* [X] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

ddev typo3cms upgrade:list 
[ RuntimeException ]   No valid wizard identifier given
Failed to run typo3cms upgrade:list --all: exit status 255

## Versions
PHP 7.4, TYPO3 Core 10.4.31 and blog Ext 11.0.2

doctrine/annotations                       1.13.3   Docblock Annotations Parser
doctrine/cache                             2.2.0    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/dbal                              2.13.9   Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                      v1.0.0   A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/event-manager                     1.1.2    The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/instantiator                      1.4.1    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                             1.2.3    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator                    2.1.25   A library for validating emails against several RFCs
enshrined/svg-sanitize                     0.15.4   An SVG sanitizer for PHP
guzzlehttp/guzzle                          6.5.8    Guzzle is a PHP HTTP client library
guzzlehttp/promises                        1.5.1    Guzzle promises library
guzzlehttp/psr7                            1.9.0    PSR-7 message implementation that also provides common utility methods
helhum/config-loader                       v0.12.5  Generic config loader with context and environment support.
helhum/typo3-console                       v6.7.4   A reliable and powerful command line interface for TYPO3 CMS
lolli42/finediff                           1.0.2    PHP implementation of a Fine granularity Diff engine
masterminds/html5                          2.7.5    An HTML5 parser and serializer.
nikic/php-parser                           v4.14.0  A PHP parser written in PHP
phpdocumentor/reflection-common            2.2.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock          5.3.0    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver                1.6.1    A PSR-5 based resolver of Class names, Types and Structural Element Names
phpstan/phpstan                            1.8.2    PHPStan - PHP Static Analysis Tool
psr/cache                                  1.0.1    Common interface for caching libraries
psr/container                              1.1.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                       1.0.0    Standard interfaces for event handling.
psr/http-client                            1.0.1    Common interface for HTTP clients
psr/http-factory                           1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                           1.0.1    Common interface for HTTP messages
psr/http-server-handler                    1.0.1    Common interface for HTTP server-side request handler
psr/http-server-middleware                 1.0.1    Common interface for HTTP server-side middleware
psr/log                                    1.1.4    Common interface for logging libraries
ralouphie/getallheaders                    3.0.3    A polyfill for getallheaders.
rector/rector                              0.13.4   Instant Upgrade and Automated Refactoring of any PHP code
symfony/cache                              v5.4.11  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts                    v2.5.2   Generic abstractions related to caching
symfony/config                             v5.4.11  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                            v5.4.11  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection               v5.4.11  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts              v2.5.2   A generic function and convention to trigger deprecation notices
symfony/event-dispatcher                   v5.4.9   Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts         v2.5.2   Generic abstractions related to dispatching event
symfony/expression-language                v5.4.11  Provides an engine that can compile and evaluate expressions
symfony/filesystem                         v5.4.11  Provides basic utilities for the filesystem
symfony/finder                             v5.4.11  Finds files and directories via an intuitive fluent interface
symfony/http-foundation                    v5.4.11  Defines an object-oriented layer for the HTTP specification
symfony/mailer                             v5.4.11  Helps sending emails
symfony/mime                               v5.4.11  Allows manipulating MIME messages
symfony/polyfill-ctype                     v1.26.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme             v1.26.0  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                  v1.26.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                  v1.26.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer           v1.26.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                  v1.26.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                     v1.26.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                     v1.26.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                     v1.26.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                     v1.26.0  Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                            v5.4.11  Executes commands in sub-processes
symfony/property-access                    v5.4.11  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                      v5.4.11  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                            v5.4.11  Maps an HTTP request to a set of configuration variables
symfony/service-contracts                  v2.5.2   Generic abstractions related to writing services
symfony/string                             v5.4.11  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/var-dumper                         v5.4.11  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                       v5.4.10  Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                               v5.4.11  Loads and dumps YAML files
t3g/blog                                   11.0.2   This blog extension uses TYPO3s core concepts and elements to provide a full-blown blog that users of TYPO3 can instantly understand and use.
twbs/bootstrap                             v4.6.2   The most popular front-end framework for developing responsive, mobile first projects on the web.
typo3/class-alias-loader                   v1.1.3   Amends the composer class loader to support class aliases to provide backwards compatibility for packages
typo3/cms-about                            v10.4.31 Shows info about TYPO3, installed extensions and a separate module for available modules.
typo3/cms-adminpanel                       v10.4.31 The TYPO3 admin panel provides a panel with additional functionality in the frontend (Debugging, Caching, Preview...)
typo3/cms-backend                          v10.4.31 Classes for the TYPO3 backend.
typo3/cms-belog                            v10.4.31 Displays backend log, both per page and system wide. Available as the module Tools>Log (system wide overview) and Web>Info/Log (page relative overview).
typo3/cms-beuser                           v10.4.31 Backend user administration and overview. Allows you to compare the settings of users and verify their permissions and see who is online.
typo3/cms-cli                              2.0.0    TYPO3 command line binary
typo3/cms-composer-installers              v3.1.2   TYPO3 CMS Installers
typo3/cms-core                             v10.4.31 The core library of TYPO3.
typo3/cms-extbase                          v10.4.31 A framework to build extensions for TYPO3 CMS.
typo3/cms-extensionmanager                 v10.4.31 TYPO3 Extension Manager
typo3/cms-felogin                          v10.4.31 A template-based plugin to log in Website Users in the Frontend
typo3/cms-filelist                         v10.4.31 Listing of files in the directory
typo3/cms-filemetadata                     v10.4.31 Add advanced metadata to File.
typo3/cms-fluid                            v10.4.31 Fluid is a next-generation templating engine which makes the life of extension authors a lot easier!
typo3/cms-fluid-styled-content             v10.4.31 A set of common content elements based on Fluid for Frontend output.
typo3/cms-form                             v10.4.31 Form Library, Plugin and Editor
typo3/cms-frontend                         v10.4.31 Classes for the frontend of TYPO3.
typo3/cms-info                             v10.4.31 Shows various infos
typo3/cms-install                          v10.4.31 The Install Tool mounted as the module Tools>Install in TYPO3.
typo3/cms-lowlevel                         v10.4.31 Enables the 'Config' and 'DB Check' modules for technical analysis of the system. This includes raw database search, checking relations, counting pages...
typo3/cms-opendocs                         v10.4.31 Shows opened documents by the user.
typo3/cms-recordlist                       v10.4.31 List of database-records
typo3/cms-recycler                         v10.4.31 The recycler offers the possibility to restore deleted records or remove them from the database permanently. These actions can be applied to a single r...
typo3/cms-redirects                        v10.4.31 Custom redirects in TYPO3.
typo3/cms-reports                          v10.4.31 The reports module groups several system reports.
typo3/cms-rte-ckeditor                     v10.4.31 Integration of CKEditor as Rich Text Editor.
typo3/cms-scheduler                        v10.4.31 The TYPO3 Scheduler let's you register tasks to happen at a specific time
typo3/cms-seo                              v10.4.31 SEO features for TYPO3.
typo3/cms-setup                            v10.4.31 Allows users to edit a limited set of options for their user profile, eg. preferred language and their name and email address.
typo3/cms-tstemplate                       v10.4.31 Framework for management of TypoScript template records for the CMS frontend.
typo3/cms-viewpage                         v10.4.31 Shows the frontend webpage inside the backend frameset.
typo3/html-sanitizer                       v2.0.15  HTML sanitizer aiming to provide XSS-safe markup based on explicitly allowed tags, attributes and values.
typo3/phar-stream-wrapper                  v3.1.7   Interceptors for PHP's native phar:// stream handling
typo3/symfony-psr-event-dispatcher-adapter v2.1.0   Adapter to provide compatibility with the Symfony's event dispatcher interface in all versions with the PSR-14 specification.
typo3fluid/fluid                           2.7.2    The TYPO3 Fluid template rendering engine
webmozart/assert                           1.11.0   Assertions to validate method input/output with nice error messages.

**Comment by helsner** [comment]
guess that's that one here?
https://github.com/TYPO3GmbH/blog/issues/39

**Comment by Andreas-Sommer** [comment]
Created a release for anyone have the same issue
https://github.com/Andreas-Sommer/blog/releases/tag/11.0.3
