### ISSUE TITLE
a connection to the Google server is established when comment option is enabled in blog post

### ISSUE THREAD

**Issue by medarob** [TYPO3GmbH/blog#26]
# Bug Report

The comments are enabled for a specific blog post.
I noticed that when I open this blog post that an instant connection to the Google-Server is established. I think that is not GDPR compliant.

![grafik](https://user-images.githubusercontent.com/33951787/52470466-7fbdb400-2b8e-11e9-89bb-3e71e433086e.png)

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS

## Description

A connection to the Google server is established, once I active the comment option for a blog post.

## Steps to Reproduce

1. open blog post and look at the console

**Expected behavior:**
I don't want a connection to the Google server.

**Comment by benjaminkott** [comment]
Thx for the report, found the issue a wrong condition. If Google ReCaptcha is now disabled in the settings there will be no request anymore.
