### ISSUE TITLE
Site with archive: unfinite redirect

### ISSUE THREAD

**Issue by criwe** [TYPO3GmbH/blog#27]
# Bug Report

## Prerequisites

* [? ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

When calling the site withe the blog_archive is on (blog/archive/), unfinite redirects are performed.
/blog/archive/2018/ is working well

[Description of the bug]

## Steps to Reproduce

1. Insert the archive plugin
2. call the site (previews or via url)
3. wait until browser stops with error

**Expected behavior:** [What you expected to happen]

Should list all years (like in the sitebar widget)

**Actual behavior:** [What actually happened]

## Versions

9.1.0

**Comment by w010** [comment]
This problem still exists in branch 8.7.
