### ISSUE TITLE
not able to alter Publish Date 

### ISSUE THREAD

**Issue by kgkgat** [TYPO3GmbH/blog#281]
# Bug Report

## Prerequisites

fresh ddev-composer-Installation
`TYPO3 Blog: Integration (blog)` configured step by step as described in manual 

## Description

when entering a new date in `Edit Post Meta-Date`, field `Publish date`, then klick Save, the original Create Date remains

## Steps to Reproduce

1. installed a new instance, same behavior

**Expected behavior:** 
want to edit publish date because need of migrating old wordpress blog to TYPO3 ;o)

**Actual behavior:** 
all the migrated blogpost have still the publishing date of today

**possible workaround**
editing directly in sql: 
I certainly won't do that ;o)))

## Versions

TYPO3 12.4.1
blog 12.0.0
PHP 8.2.3
MariaDB 10.4.28

**Comment by kgkgat** [comment]
tried in TYPO3 v11 (clean composer install): working
tried in TYPO3 v12 (updated from clean v11 composer install): not working
😥

**Comment by Jake-double-one** [comment]
I have the same problem with integration setup on TYPO3 v11.5.27.
The published date cannot set to anything else than the time, when you hit save.
![image](https://github.com/TYPO3GmbH/blog/assets/82903707/a37fc1c8-4b57-477a-91b4-f98c6299073f)

**Comment by alexanderstier** [comment]
I have the same problem with blog v12.0.0 on existing Typo3 Installation after migrating to v11.5.26
The publish date cannot be saved to database, it will be set to actual timestamp on saving.

**Comment by PLACEBOBRO** [comment]
Also reproducable for me in TYPO3 v12.4.2. Can't set publish date, because it gets set to current date on save

**Comment by LeoniePhiline** [comment]
In the mean time, you can use [the fix](https://github.com/TYPO3GmbH/blog/pull/283) before `12.0.1` is released:

`composer.json` (excerpt):

```diff
 {
   "repositories": [
     { "type": "composer", "url": "https://composer.typo3.org/" },
+    { "type": "git", "url": "https://github.com/LeoniePhiline/blog" }
   ],
  "require": {
-    "t3g/blog": "12.0.0",
+    "t3g/blog": "dev-fix/281",
   }
 }
```
