### ISSUE TITLE
Archive: unfinite redirect

### ISSUE THREAD

**Issue by w010** [TYPO3GmbH/blog#37]
# Bug Report

## Prerequisites

* [X] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

https://github.com/TYPO3GmbH/blog/issues/27

This issue might be fixed for 9.x but still occurs in v8.7 branch.
Details are in link.

## Versions

8.7.3
8.7.4-dev

**Comment by benjaminkott** [comment]
Backport in 8.7 done. Thx for the report - we missed that.
