### ISSUE TITLE
How to render Image from Blog Page Resources

### ISSUE THREAD

**Issue by chequille** [TYPO3GmbH/blog#38]
Hi Everybody,
using Typo3 7.6.31 at the moment and the according blog extension working with this Typo version.

Trying to make some own templates for the extension.
I want to show an image which is specified under the blog page Resource Tab.
In my template "Post.html" I want to show this image.
Debugging of {post.media} shows the follwing:
![grafik](https://user-images.githubusercontent.com/15807794/52978704-ae2f6080-33d2-11e9-8fab-c66f24cfcb08.png)
I could show the image when typing manually <f:image src="525" treatIdAsReference="1" />, but I do not know how to get the uid out of {post.media}.

Does somebody know this and can help me?

Regards,
Chequille

**Comment by benjaminkott** [comment]
Can you check if `<f:image image="{post.media}" />` is working?

**Comment by chequille** [comment]
Hi,
did that already. No, it is not working. Was my first thought as well but not working.

**Comment by chequille** [comment]
The only way I got the image rendered was <f:image src="525" treatIdAsReference="1" /> as already mentioned.

**Comment by benjaminkott** [comment]
mm.. i missed that this is a object storage...

```
<f:for each="{post.media}" as="media">
    <f:image image="{post.media}" />
</f:for>
```

**Comment by chequille** [comment]
Hi Benjamin,
thank you very much. Of course, this was the solution.
Sometimes the easy things are far away and you don't see them.
THanks and best regards,
Chequille

**Comment by benjaminkott** [comment]
But also try `<f:image image="{post.media.0}" />` not sure if that's working but we are using it that way in recent versions.

**Comment by chequille** [comment]
this is also working.
Only one problem left. It is shown with the original size and is not responsive.
Maybe if have to use another viewhelper?

**Comment by benjaminkott** [comment]
Depends on how you want to display it?

```
<f:if condition="{post.media.0}">
  <f:image image="{post.media.0}" class="img-responsive" height="300c" width="300" />
</f:if>
```

**Comment by chequille** [comment]
Perfect !!!
I can work with it now.
Thanks again.
