### ISSUE TITLE
RSS link for the whole blog.

### ISSUE THREAD

**Issue by p410n3** [TYPO3GmbH/blog#40]
# RSS

After searching the extension manual, various articles and this repos Issues, I was unable to find a way to have all posts of a blog in ONE RSS feed. I would assume there is a link for that already, because there is one for every category, author and specific time frames (e.g. a certain month) which I was able to find in the template itself.

If thats the case, that's missing from the extension manual as well.

Thanks in advance, and for that pretty cool extension, 

Phillip

**Comment by NeoBlack** [comment]
Sure there is an RSS feed for all posts. Try pageType 200 with the default setup.

You can find the setup here:
https://github.com/TYPO3GmbH/blog/blob/a055325fb905cdf51fcf546cbbdbc8592cc7d849/Configuration/TypoScript/Static/setup.typoscript#L150-L166

**Comment by p410n3** [comment]
I see. So:

````
https://my.domain.tld?type=200
````

Works perfectly. I personally would like that to be added top the manual, but thats not my decision to make. 

Thanks @NeoBlack
