### ISSUE TITLE
Content Layout for Blog Plugins

### ISSUE THREAD

**Issue by chequille** [TYPO3GmbH/blog#46]
Hi,
I wanted to ask if this is already possible or not.
I do want to use the content element "Blog List by Category" as content element on a Blog Page.
Of course, this is working but I do want to have a different template for it because it should be rendered differently.
With other content elements, I can define in TCFORM layouts which can be selected under appearance -> content layout.
In the fluid template I can read this value and can decide which rendering should be done.
Is this possible as well with the blog extension?
If yes, how can I get the value in the fluid template?

Currently, I solved this with setting a new path for the fluid templates via Typoscript for the Blog Page, but this is not very user friendly.

I hope there is some solution for this and I am looking forward to hearing from you.
Best regards,
Jürgen

**Comment by benjaminkott** [comment]
@chequille please see: https://github.com/TYPO3GmbH/blog/blob/master/Classes/Controller/PostController.php#L140

We added `{data}` a while ago so you should be able to access these information and adapt the templates to your needs.

**Comment by chequille** [comment]
Hi Benjamin,
might be, that this is working already, but I still do not know how to define layouts which can be than selected as in the screenshot
![grafik](https://user-images.githubusercontent.com/15807794/79118183-6a917600-7d8d-11ea-9c8e-a148d27aec77.png)
For tt_content elements i can do this in TCEFORM.tsconfig but I do not know how to do this for the Blog elements.
Do you have a sample how to do this?
BR
Chequille

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
As far as I know adding items to tt_content.layout is only possible for CTypes. The blog elements have CType "list" with a specific list_type like "blog_demandedposts". So it's not possible.

Workaround: You can add a new layout in TCEFORM for list, but then you'll see it in all list elements. Make wording specific, so integrators know where it applies.

Better solutions: Best would be to extend typo3 core with the possibility to change layouts for specific list_types. Another solution is to have an own layout field (flexform) like in the news-extension.

Please re-open. ;-)
