### ISSUE TITLE
Evaluate EXT:repair_translation

### ISSUE THREAD

**Issue by susannemoog** [TYPO3GmbH/blog#53]
The extension repair_translation fixes an issue in core v8 which could be helpful for EXT:blog as well.
Read up the discussion in slack:
https://typo3.slack.com/archives/C1XLMLRM1/p1550571695097400

If it makes sense we could suggest or require the extension for v8 branch.

[Moved from TGT-1667]

**Comment by mbrodala** [comment]
Copy from the Slack discussion for reference:

> **Oana Johner** [11:21 AM]
*Q:* I'm not sure if this is a problem of `EXT:blog` or general regarding localization of images. I feel a bit confused. Using latest dev version of `EXT:blog` and TYPO3 8.7.24. When using a list of posts plugin in a localized page and pointing to a folder with posts pages that are localized, I find that the `media` field has 1 item when debugging, but when I open it, it is empty :thinking_face: The record `{post}` is the localized page. And file reference inside that post page exists. What could cause this issue? I don't see anything remarkable > in the `Post` model (just `@lazy` annotation for property `media`).
> 2019.02.19-11-17-42.png 
> 
> 
> 
> **Mathias wild Brodala - mbrodala** [11:23 AM]
> Can you retry with EXT:repair_translation?
> In TYPO3v9 and newer you could benefit from the consistent translation handling:
> https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Important-82363-MakeExtBaseTranslationHandlingConsistentWithTyposcript.html
> 
> **Mathias Schreiber** [11:24 AM]
> I’m not even 100% sure that we support (or want to support) localized Posts.
> 
> **Oana Johner** [11:25 AM]
> Why not? :disappointed:
> 
> **Mathias Schreiber** [11:26 AM]
> from our experience, blogs are such a fast moving channel of content that the classic “translation workflow” makes little sense.
> 
> **Oana Johner** [11:26 AM]
> Ah, you mean in the extension @mbrodala suggested.
> 
> **Mathias Schreiber** [11:27 AM]
> no, I meant the blog itself.
> Our suggestion is to have a dedicated Storage Folder per Language
> 
> **Oana Johner** [11:27 AM]
> And I have a dedicated storage folder per Language indeed!
> 
> **Mathias Schreiber** [11:27 AM]
> where do the translations come from, then? :slightly_smiling_face:
> ah!
> 
> **Oana Johner** [11:28 AM]
But as it didn't work for me to point from a list of posts plugin (in a localized page) to this dedicated storage folder with default posts, I presumed it had to work with localized > posts.
> 
> **Mathias Schreiber** [11:28 AM]
> now I got it
> my bad, my bad
> so the blog listing page is localized (not the posts themselves) and the list plugin does not grab the images correctly
> did I get that right so far?
> 
> **Oana Johner** [11:28 AM]
> That's it, right.
> 
> **Mathias Schreiber** [11:29 AM]
> @neoblack @benjaminkott do you by chance know if we have a report for that?
> 
> **Oana Johner** [11:29 AM]
> That's funny, because for the default blog listing page, media files are taken, like the rest of the fields.
> 
> **Frank Nägler** [11:41 AM]
> not sure, will check this issue tracker
> 
> **Oana Johner** [11:41 AM]
> Just FYI: we got configured `config.sys_language_mode = strict` & `config.sys_language_overlay = 1`.
> Thanks for taking a look!
> 
> **Frank Nägler** [11:44 AM]
I see no media translation related issue int the tracker (https://github.com/TYPO3GmbH/blog/issues) we have the known open issue regarding resolving the current post in multilanguage > setups,
> 
> **Oana Johner** [11:46 AM]
> The truth is that extension suggested by Mathias Brodala `EXT:repair_translation` just worked. It seems this is a generic problem just related to TYPO3 8.7 ? :thinking_face:
> 
> **Frank Nägler** [11:47 AM]
> yes, it is possible, I don't know the extension, but will check the extension.
> 
> **Frank Nägler** [11:56 AM]
> @Oana Johner it would be nice if you could create an issue in the tracker with a short description of the issue and the solution, we will evaluate this for future versions.
> 
> **Oana Johner** [11:56 AM]
> Great. I'll do that! Thanks for your support.
> 
> **Frank Nägler** [11:57 AM]
> thank you for the report

**Comment by benjaminkott** [comment]
As discussed with @susannemoog this can be closed.
