### ISSUE TITLE
renaming categories deletes category from news record

### ISSUE THREAD

**Issue by medarob** [TYPO3GmbH/blog#81]
Hi there,

I have a strange bug and maybe someone can confirm this behaviour:

# Bug Report

I wanted to rename a category from a news article (EXT:news) and everytime the category was deleted from every news article where the category was used. So I have over 100 news articles and this category I wanted to rename was deleted from every article...

I deactivated almost every extension and finally, with EXT:blog deactivated, the renaming worked.
The workaround is now, everytime I want to rename a category which is used in a news article I have to deactivate the blog extension first. Rename the category and then activate the blog again.
This is not very practical...Also editors don't have permissions to activate/deactivate extensions.

Renaming categories which I use inside a blog post works without deleting anything... So I wonder what causes this problem?

## Prerequisites

* [x ] Can you reproduce the problem on TYPO3 v8.7.25 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Steps to Reproduce

Install EXT:news and EXT:blog and try to rename a category used in a news article. Would be nice if someone can confirm this issue...

**Expected behavior:** 
I would like that the categories I use inside the news extension are not deleted when I rename them and EXT:blog is activated.

**Actual behavior:** 

The category I want to rename is deleted from every news article where this category is used.

## Versions

TER version TYPO3 8.7.25
news 7.2
blog: 8.7.4

**Comment by medarob** [comment]
We updated our system to TYPO3 9.5 (with the latest EXT:blog and EXT:news) and the error still exists.

Has anyone an idea why this happens and how it's possible to finde the problem?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
You don't necessarily have to rename the categories. It already happens if you just save the category. After some tests I found out that the causing file is

typo3conf/ext/blog/Configuration/TCA/Overrides/sys_category.php

There $temporaryColumns['posts']['config']['MM'] is set to 'sys_category_record_mm'.

If you set that value to an empty string or false, the record-relations won't be deleted anymore. Like medarob wrote: If you deactivate the blog extension, all is fine. A fix is appreciated.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
"Little" sideeffect: Blog throws an exception then. :-D

ConnectionPool->getQueryBuilderForTable() requires a connection name to be provided.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
We testet the patch and the categories won't get deleted anymore. Blog works, too. Thank you Alex! Don't know about possible sideeffects though.

**Comment by andreasfernandez** [comment]
Hello,

I tried to reproduce this issue with TYPO3 v10.4.12, EXT:news 8.5.0 and EXT:blog 10.0 and failed so far. Can you please check whether this issue has been solved meanwhile?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi,

I can do so, but at the moment we only have TYPO3 9.5, latest News and Blog 9.x installed. Should I test on that configuration or wait till we are on Blog 10 and/or TYPO3 10? This could last a few weeks.

The patch from alexkue7911 works since then.

**Comment by andreasfernandez** [comment]
Hi,

I managed to reproduce the issue now. The key point is that the category must be of type "Blog category", it seems. I'll update @alexkue7911's patch and merge it right away.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
thank you!
