### ISSUE TITLE
Mail after comment throws error in master

### ISSUE THREAD

**Issue by maddy2101** [TYPO3GmbH/blog#90]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

After https://review.typo3.org/c/Packages/TYPO3.CMS/+/61152 writing a comment will result in Fatal error: Class 'Symfony\Component\Mime\Email' not found in /var/www/html/typo3/sysext/core/Classes/Mail/MailMessage.php on line 27 in frontend with core master and extension master

## Steps to Reproduce

1. create a blog post
2. comment on the post
3. see the error after submitting the comment

## Versions

master core and master extension

**Comment by Mesaman** [comment]
I also get an error after filling out the form and tying to send a comment but it comes from localization in my case. This is the error message:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of T3G\AgencyPack\Blog\Notification\CommentAddedNotification::getLanguageService() must be an instance of TYPO3\CMS\Core\Localization\LanguageService, null returned`

**Comment by unltdnetworx** [comment]
I am using the master branch with Typo3 10.3.0, no template-extension.
After sending a comment, the e-mail apllication throws the follwing error.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to Symfony\Component\Mime\Message::setBody() must be an instance of Symfony\Component\Mime\Part\AbstractPart or null, string given, called in /var/www/.../html/typo3conf/ext/blog/Classes/Notification/Processor/AdminNotificationProcessor.php on line 53 | TypeError thrown in file /var/www/.../sources/typo3_src-10.3.0/vendor/symfony/mime/Message.php in line 45.`

The are no changes on the original e-mail-template. Seems like the body is in a wrong format.

Other Extensions correctly send mails.
